services:
  tane_chat:
    image: tanep/tane_chat:latest
    ports:
      # ローカルのポート5005をコンテナ内のポート5005にマッピング
      # <ホストポート>:<コンテナポート>の指定です。コンテナポートは変更しないで下さい。
      - "5005:5005"  
    environment:
      - MODEL_PATH=/app/model           # モデルのパスを指定（ここは変更しないで下さい。）
      - N_THREADS=2                     # スレッド数
      - CHAT_FORMAT=llama-3             # チャットフォーマット
      - N_CTX=512                       # コンテキストサイズ
      - BATCH_SIZE=512                  # バッチサイズ
      - NUM_WORKERS=2                   # ワーカー数
      - PORT=5005                       # Flaskアプリケーションのポート（ここは変更しないで下さい。）
    restart: always  # PC再起動後に自動でコンテナを再起動
    volumes:
      - /LLMのggufファイルを置いているパス:/app/model  # モデルファイルをコンテナにマウント
    tty: true  # ターミナルのインタラクションを有効にするための設定（必要に応じて）

